[tool.poetry]
name = "uns-py-app"
version = "0.1.0"
description = "Example UNS Python application"
authors = ["Your Name <you@example.com>"]
packages = [{ include = "uns_py_app" }]

[tool.poetry.dependencies]
python = "^3.10"
uns-kit = "*"
# Pin MQTT libs to versions compatible with asyncio-mqtt 0.16.x
paho-mqtt = "<2"
asyncio-mqtt = "0.16.2"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[tool.poetry.scripts]
dev = "uns_kit.cli:main"
run = "uns_kit.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
