[tool.poetry]
name = "uns-py-app"
version = "0.1.0"
description = "Example UNS Python application"
authors = ["Your Name <you@example.com>"]
packages = [{ include = "uns_py_app" }]

[tool.poetry.dependencies]
python = "^3.10"
uns-kit = "*"
aiomqtt = "^2.4.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
